name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current date
        id: get_date
        run: echo "RELEASE_DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_ENV

      - name: Set environment variables
        id: vars
        run: |
          echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body: |
            # 📌 What's New
            🌟 This release includes new features and improvements.

            **👉 Release Date:** ${{ env.RELEASE_DATE }}

            **👉 Recent Commit:** ${{ github.event.head_commit.message }}

            **👉 Commit:** [${{ env.COMMIT_SHA }}](https://github.com/${{ env.REPO_NAME }}/commit/${{ env.COMMIT_SHA }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}